schedule/urls.py
from django.conf.urls.defaults import *
from django.views.generic.list_detail import object_list
from schedule.models import Room
from schedule.feeds import UpcomingReservationsFeed
from schedule.feeds import RoomIRoom
from schedule.periods import Year, Month, Week, Day

info_dict = {
    'queryset': Room.objects.all(),
}

urlpatterns = patterns('',

# urls for Rooms
url(r'^room/$',
    object_list,
    name="schedule",
    kwargs={'queryset':Room.objects.all(), 'template_name':'schedule/room_list.html'}),

url(r'^room/year/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name="year_room",
    kwargs={'periods': [Year], 'template_name': 'schedule/room_year.html'}),

url(r'^room/tri_month/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name="tri_month_room",
    kwargs={'periods': [Month], 'template_name': 'schedule/room_tri_month.html'}),

url(r'^room/compact_month/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name = "compact_room",
    kwargs={'periods': [Month], 'template_name': 'schedule/room_compact_month.html'}),

url(r'^room/month/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name = "month_room",
    kwargs={'periods': [Month], 'template_name': 'schedule/room_month.html'}),

url(r'^room/week/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name = "week_room",
    kwargs={'periods': [Week], 'template_name': 'schedule/room_week.html'}),

url(r'^room/daily/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room_by_periods',
    name = "day_room",
    kwargs={'periods': [Day], 'template_name': 'schedule/room_day.html'}),

url(r'^room/(?P<room_slug>[-\w]+)/$',
    'schedule.views.room',
    name = "room_home",
    ),

#Reservation Urls
url(r'^reservation/create/(?P<room_slug>[-\w]+)/$',
    'schedule.views.create_or_edit_reservation',
    name='room_create_reservation'),
url(r'^reservation/edit/(?P<room_slug>[-\w]+)/(?P<reservation_id>\d+)/$',
    'schedule.views.create_or_edit_reservation',
    name='edit_reservation'),
url(r'^reservation/(?P<reservation_id>\d+)/$',
    'schedule.views.reservation',
    name="reservation"), 
url(r'^reservation/delete/(?P<reservation_id>\d+)/$',
    'schedule.views.delete_reservation',
    name="delete_reservation"),

#urls for already persisted occurrences
url(r'^occurrence/(?P<reservation_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.occurrence',
    name="occurrence"), 
url(r'^occurrence/cancel/(?P<reservation_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.cancel_occurrence',
    name="cancel_occurrence"),
url(r'^occurrence/edit/(?P<reservation_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.edit_occurrence',
    name="edit_occurrence"),

#urls for unpersisted occurrences
url(r'^occurrence/(?P<reservation_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.occurrence', 
    name="occurrence_by_date"),
url(r'^occurrence/cancel/(?P<reservation_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.cancel_occurrence', 
    name="cancel_occurrence_by_date"),
url(r'^occurrence/edit/(?P<reservation_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.edit_occurrence', 
    name="edit_occurrence_by_date"),
    

#feed urls 
url(r'^feed/room/(.*)/$',
    'django.contrib.syndication.views.feed', 
    { "feed_dict": { "upcoming": UpcomingReservationsFeed } }),
 
(r'^ical/room/(.*)/$', RoomIRoom()),

 url(r'^$', object_list, info_dict, name='schedule'), 
)

schedule/models/reservations.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes import generic
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.template.defaultfilters import date
from django.utils.translation import ugettext, ugettext_lazy as _
import datetime
from dateutil import rrule
from schedule.models.rules import Rule
from schedule.models.rooms import Room
from schedule.utils import OccurrenceReplacer

class ReservationManager(models.Manager):

    def get_for_object(self, content_object, distinction=None, inherit=True):
        return ReservationRelation.objects.get_reservations_for_object(content_object, distinction, inherit)

class Reservation(models.Model):
    '''
    This model stores meta data for a date.  You can relate this data to many
    other models.
    '''
    start = models.DateTimeField(_("start"))
    end = models.DateTimeField(_("end"),help_text=_("The end time must be later than the start time."))
    title = models.CharField(_("title"), max_length = 255)
    description = models.TextField(_("description"), null = True, blank = True)
    creator = models.ForeignKey(User, null = True, verbose_name=_("creator"))
    created_on = models.DateTimeField(_("created on"), default = datetime.datetime.now)
    rule = models.ForeignKey(Rule, null = True, blank = True, verbose_name=_("rule"), help_text=_("Select '----' for a one time only reservation."))
    end_recurring_period = models.DateTimeField(_("end recurring period"), null = True, blank = True, help_text=_("This date is ignored for one time only reservations."))
    room = models.ForeignKey(Room, blank=True, null=True)
    objects = ReservationManager()

    class Meta:
        verbose_name = _('reservation')
        verbose_name_plural = _('reservations')
        app_label = 'schedule'
	get_latest_by = 'start' 

    def __unicode__(self):
        date_format = u'l, %s' % ugettext("DATE_FORMAT")
        return ugettext('%(title)s: %(start)s-%(end)s') % {
            'title': self.title,
            'start': date(self.start, date_format),
            'end': date(self.end, date_format),
        }

    def get_absolute_url(self):
        return reverse('reservation', args=[self.id])

    def create_relation(self, obj, distinction = None):
        """
        Creates a ReservationRelation between self and obj.
        """
        ReservationRelation.objects.create_relation(self, obj, distinction)

    def get_occurrences(self, start, end):
        """
        >>> rule = Rule(frequency = "MONTHLY", name = "Monthly")
        >>> rule.save()
        >>> reservation = Reservation(rule=rule, start=datetime.datetime(2008,1,1), end=datetime.datetime(2008,1,2))
        >>> reservation.rule
        <Rule: Monthly>
        >>> occurrences = reservation.get_occurrences(datetime.datetime(2008,1,24), datetime.datetime(2008,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        ['2008-02-01 00:00:00 to 2008-02-02 00:00:00', '2008-03-01 00:00:00 to 2008-03-02 00:00:00']

        Ensure that if an reservation has no rule, that it appears only once.

        >>> reservation = Reservation(start=datetime.datetime(2008,1,1,8,0), end=datetime.datetime(2008,1,1,9,0))
        >>> occurrences = reservation.get_occurrences(datetime.datetime(2008,1,24), datetime.datetime(2008,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        []

        """
        persisted_occurrences = self.occurrence_set.all()
        occ_replacer = OccurrenceReplacer(persisted_occurrences)
        occurrences = self._get_occurrence_list(start, end)
        final_occurrences = []
        for occ in occurrences:
            # replace occurrences with their persisted counterparts
            if occ_replacer.has_occurrence(occ):
                p_occ = occ_replacer.get_occurrence(
                        occ)
                # ...but only if they are within this period
                if p_occ.start < end and p_occ.end >= start:
                    final_occurrences.append(p_occ)
            else:
              final_occurrences.append(occ)
        # then add persisted occurrences which originated outside of this period but now
        # fall within it
        final_occurrences += occ_replacer.get_additional_occurrences(start, end)
        return final_occurrences

    def get_rrule_object(self):
        if self.rule is not None:
            params = self.rule.get_params()
            frequency = rrule.__dict__[self.rule.frequency]
            return rrule.rrule(frequency, dtstart=self.start, **params)

    def _create_occurrence(self, start, end=None):
        if end is None:
            end = start + (self.end - self.start)
        return Occurrence(reservation=self,start=start,end=end, original_start=start, original_end=end)

    def get_occurrence(self, date):
        rule = self.get_rrule_object()
        if rule:
            next_occurrence = rule.after(date, inc=True)
        else:
            next_occurrence = self.start
        if next_occurrence == date:
            try:
                return Occurrence.objects.get(reservation = self, original_start = date)
            except Occurrence.DoesNotExist:
                return self._create_occurrence(next_occurrence)


    def _get_occurrence_list(self, start, end):
        """
        returns a list of occurrences for this reservation from start to end.
        """
        difference = (self.end - self.start)
        if self.rule is not None:
            occurrences = []
            if self.end_recurring_period and self.end_recurring_period < end:
                end = self.end_recurring_period
            rule = self.get_rrule_object()
            o_starts = rule.between(start-difference, end, inc=False)
            for o_start in o_starts:
                o_end = o_start + difference
                occurrences.append(self._create_occurrence(o_start, o_end))
            return occurrences
        else:
            # check if reservation is in the period
            if self.start < end and self.end >= start:
                return [self._create_occurrence(self.start)]
            else:
                return []

    def _occurrences_after_generator(self, after=None):
        """
        returns a generator that produces unpresisted occurrences after the
        datetime ``after``.
        """

        if after is None:
            after = datetime.datetime.now()
        rule = self.get_rrule_object()
        if rule is None:
            if self.end > after:
                yield self._create_occurrence(self.start, self.end)
            raise StopIteration
        date_iter = iter(rule)
        difference = self.end - self.start
        while True:
            o_start = date_iter.next()
            if o_start > self.end_recurring_period:
                raise StopIteration
            o_end = o_start + difference
            if o_end > after:
                yield self._create_occurrence(o_start, o_end)


    def occurrences_after(self, after=None):
        """
        returns a generator that produces occurrences after the datetime
        ``after``.  Includes all of the persisted Occurrences.
        """
        occ_replacer = OccurrenceReplacer(self.occurrence_set.all())
        generator = self._occurrences_after_generator(after)
        while True:
            next = generator.next()
            yield occ_replacer.get_occurrence(next)
    
    def next_occurrence(self):
        for o in self.occurrences_after():
            return o
    

class ReservationRelationManager(models.Manager):
    '''
    >>> ReservationRelation.objects.all().delete()
    >>> RoomRelation.objects.all().delete()
    >>> data = {
    ...         'title': 'Test1',
    ...         'start': datetime.datetime(2008, 1, 1),
    ...         'end': datetime.datetime(2008, 1, 11)
    ...        }
    >>> Reservation.objects.all().delete()
    >>> reservation1 = Reservation(**data)
    >>> reservation1.save()
    >>> data['title'] = 'Test2'
    >>> reservation2 = Reservation(**data)
    >>> reservation2.save()
    >>> user1 = User(username='alice')
    >>> user1.save()
    >>> user2 = User(username='bob')
    >>> user2.save()
    >>> reservation1.create_relation(user1, 'owner')
    >>> reservation1.create_relation(user2, 'viewer')
    >>> reservation2.create_relation(user1, 'viewer')
    '''
    # Currently not supported
    # Multiple level reverse lookups of generic relations appears to be
    # unsupported in Django, which makes sense.
    #
    # def get_objects_for_reservation(self, reservation, model, distinction=None):
    #     '''
    #     returns a queryset full of instances of model, if it has an ReservationRelation
    #     with reservation, and distinction
    #     >>> reservation = Reservation.objects.get(title='Test1')
    #     >>> ReservationRelation.objects.get_objects_for_reservation(reservation, User, 'owner')
    #     [<User: alice>]
    #     >>> ReservationRelation.objects.get_objects_for_reservation(reservation, User)
    #     [<User: alice>, <User: bob>]
    #     '''
    #     if distinction:
    #         dist_q = Q(reservationrelation__distinction = distinction)
    #     else:
    #         dist_q = Q()
    #     ct = ContentType.objects.get_for_model(model)
    #     return model.objects.filter(
    #         dist_q,
    #         reservationrelation__content_type = ct,
    #         reservationrelation__reservation = reservation
    #     )

    def get_reservations_for_object(self, content_object, distinction=None, inherit=True):
        '''
        returns a queryset full of reservations, that relate to the object through, the
        distinction

        If inherit is false it will not consider the rooms that the reservations
        belong to. If inherit is true it will inherit all of the relations and

schedule/templates/schedule/_daily_table.html
{% load scheduletags %}
  <div class="slot_column" style="width:{{width_slot}}px;height:{{height}}px;">
    {% for slot in slots %}
    <div class="slot" style="top:{{slot.top}}px;height:{{slot.height}}px;width:{{width}}px;">
      <span class="time">{{ slot.start|time:"G:i" }}</span>
      {% if addable %}
      {% create_reservation_url room slot.start %}
      {% endif %}
    </div>
    {% endfor %}
  </div>
  <div class="occ_column" style="left:{{width_slot}}px;width:{{width_occ}}px;height:{{height}}px;">
  {% for occ in occurrences %}
      <div href="#{% hash_occurrence occ %}" class="occ type{{occ.cls}}{% if occ.cancelled %} cancelled{% endif %}" 
      style="top:{{occ.top}}px;left:{{occ.left}}px;width:{{occ.width}}px;height:{{occ.height}}px;" onclick="openDetail(this);">
        {% options occ %}
        {% title occ %}

      </div>
      <div id="{% hash_occurrence occ %}" style="display:none;">
        {% detail occ %}
      </div>
  {% endfor %}
  </div>

schedule/templates/schedule/_day_cell.html
{% load scheduletags %}
{% ifnotequal day.start.month month.start.month %}
  <td class="{{size}} daynumber noday"></td>
{% else %}
  {% if day.has_occurrences %}
    <td class="{{size}} daynumber busy">
  {% else %}
    <td class="{{size}} daynumber free">
{% endif %}
    <div class="header">
        <a href="{% url day_room room.slug %}{% querystring_for_date day.start 3 %}">
            <b>{{day.start.day}}</b>
        </a>
    </div>
    {% ifnotequal size "small" %}
        <div class="daycell">
            {% if day.has_occurrences %}
                {% for o in day.get_occurrence_partials %}
                        <div class="reservationcell reservationcell{{o.class}}{% if o.occurrence.cancelled %} cancelled{% endif %}" 
                            href="#{% hash_occurrence o.occurrence %}" onclick="openDetail(this);">
                            <div class="starttime">
                                {% ifequal o.class 0 %}{{ o.occurrence.start|time:"G:i" }}{% endifequal %}
                                {% ifequal o.class 1 %}{{ o.occurrence.start|time:"G:i" }}{% endifequal %}
                                {% ifequal o.class 2 %}(All day){% endifequal %}
                                {% ifequal o.class 3 %}Ends at {{ o.occurrence.end|time:"G:i" }}{% endifequal %}
                            </div>
                            <div class="reservationdesc">
                                {% title o.occurrence %}
                            </div>
                        </div>
                        <div id="{% hash_occurrence o.occurrence %}" style="display:none;">
                          {% detail o.occurrence %}
                        </div>
                {% endfor %}
            {% endif %}
        </div>
    {% endifnotequal %}
</td>
{% endifnotequal %}

schedule/templates/schedule/_detail.html
{% load i18n %}
<div class="detail">
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
    <tr>
        <td class="left">Starts</td>
        <td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
    </tr>
    <tr>
        <td class="left">Ends</td>
        <td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
    </tr>
	<tr>
        <td class="left">Creator</td>
        <td>{% blocktrans with occurrence.reservation.creator as creator %}{{ creator }}{% endblocktrans %}</td>
    </tr>
	<tr>
        <td class="left">Created on</td>
        <td>{% blocktrans with occurrence.reservation.created_on as created_on %}{{ created_on }}{% endblocktrans %}</td>
    </tr>
    {% if occurrence.reservation.rule %}
        {% if not occurrence.id %}
            <tr>
                <td class="left">Reoccurs</td><td>{{occurrence.reservation.rule}}</td>
            </tr>
            {% if occurrence.reservation.end_recurring_period %}
                <tr>
                    <td class="left">Until</td>
                    <td>{% blocktrans with occurrence.reservation.end_recurring_period|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
                </tr>
            {% endif %}
        {% endif %}
    {% endif %}
</table>
{% if occurrence.description %}
<h3>Description</h3>
<p>{{occurrence.description}}</p>
{% endif %}
</div>

schedule/templates/schedule/cancel_occurrence.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans "Delete" %}</h1>
{% trans "Are you sure that you really want to cancel this occurrence?" %}

<form action="." method="POST">
    <h2>{{ occurrence.title }}</h2>
    <strong>From</strong> {{ occurrence.start|date:_("DATETIME_FORMAT") }}
    <strong>to</strong> {{ occurrence.end|date:_("DATETIME_FORMAT") }} <br/>
    <input type="submit" value="{% trans "Delete" %}" name="submit" />
    <input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
    <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

schedule/templates/schedule/create_reservation.html
{% extends "schedule/reservation_form_base.html" %}
{% load i18n %}

{% block head_title%}{{ room }} - Reserve Room{% endblock %}

{% block body %}
<h2>{{room}} - Reserve Room</h2>
<b>{% trans " All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
<table>
{{ form.as_table }}
</table>
<br/>
<input type="submit" value="{% trans "Save" %}">
<input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
<input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

schedule/templates/schedule/delete_reservation.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans "Delete" %}</h1>
{% trans "Are you sure that you really want to delete it?" %}

<form action="." method="POST">
    {{ object }} <br/>
    <input type="submit" value="{% trans "Delete" %}" />
    <input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>

    <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

schedule/templates/schedule/edit_occurrence.html
{% extends "schedule/reservation_form_base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change occurrence. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
<table>
{{ form.as_table }}
</table>
<br/>
<input type="submit" value="{% trans "Save" %}">
<input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
<input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

schedule/templates/schedule/occurrence.html
{% extends "base.html" %}
{% load i18n %}
{% load scheduletags %}

{% block body %}
<div class="navigation">
  <a href="{% url day_room occurrence.reservation.room.slug %}{% querystring_for_date occurrence.start 3 %}">
    Day
  </a>
  <a href="{% url month_room occurrence.reservation.room.slug %}{% querystring_for_date occurrence.start 2 %}">
    Month
  </a>
</div>
<div class="reservation_actions" align="center">
	{% if back_url %}
	<a href="{{ back_url }}"><img border="0" src="{{ MEDIA_URL }}schedule/img/left_mod.png" alt="{% trans "Back" %}"></a> &nbsp;
	{% endif %}
	{% ifequal occurrence.reservation.creator request.user %}
	<a href="{{occurrence.get_edit_url}}"><img border="0" src="{{ MEDIA_URL }}schedule/img/pencil.png" alt="{% trans "Change" %}"></a> &nbsp;
	<a href="{{occurrence.get_cancel_url}}"><img border="0" src="{{ MEDIA_URL }}schedule/img/delete.png" alt="{% trans "Cancel" %}"></a>
	{% endifequal %}
</div>
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
<tr>
<td>Starts</td>
<td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Ends</td>
<td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Creator</td>
<td>{% blocktrans with occurrence.creator as creator %}{{ creator }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Created on</td>
<td>{% blocktrans with occurrence.created_on as created_on %}{{ created_on }}{% endblocktrans %}</td>
</tr>
{% if occurrence.reservation.rule %}
<tr>
<td>Reoccurs</td><td>{{reservation.rule}}</td>
</tr>
{% endif %}
</table>
{% if occurrence.description %}
<h3>Description</h3>
<p>{{occurrence.description}}</p>
{% endif %}

{% endblock %}

schedule/templates/schedule/reservation.html
{% extends "base.html" %}
{% load i18n %}
{% load scheduletags %}

{% block body %}

<div class="navigation">
  <a href="{% url day_room reservation.room.slug %}{% querystring_for_date reservation.start 3 %}">
    Day
  </a>
  <a href="{% url month_room reservation.room.slug %}{% querystring_for_date reservation.start 2 %}">
    Month
  </a>
</div>

<div class="reservation_actions" align="center">
  {% if back_url %}
  <a href="{{ back_url }}">
    <img border="0" src="{{ MEDIA_URL }}schedule/img/left_mod.png" alt="{% trans "Back" %}"/>
  </a>
  &nbsp;
  {% endif %}
  {% ifequal reservation.creator request.user %}
  <a href="{% url edit_reservation reservation.room.slug,reservation.id %}">
    <img border="0" src="{{ MEDIA_URL }}schedule/img/pencil.png" alt="{% trans "Change" %}"/>
  </a>
  &nbsp;
  <a href="{% url delete_reservation reservation.id %}">
    <img border="0" src="{{ MEDIA_URL }}schedule/img/delete.png" alt="{% trans "Delete" %}"/>
  </a>
  {% endifequal %}
</div>
<h2 align="center">{{reservation.title}}</h2>
<table align="center">
<tr>
<td>Starts</td>
<td>{% blocktrans with reservation.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Ends</td>
<td>{% blocktrans with reservation.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Creator</td>
<td>{% blocktrans with reservation.creator as creator %}{{ creator }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Created on</td>
<td>{% blocktrans with reservation.created_on as created_on %}{{ created_on }}{% endblocktrans %}</td>
</tr>
<tr>
<td>Reoccurs</td>
{% if reservation.rule %}
<td>{{ reservation.rule }} until {% blocktrans with reservation.end_recurring_period|date:_("DATETIME_FORMAT") as end_recurring_date %}{{ end_recurring_date }}{% endblocktrans %}</td>
{% else %}
<td>{% trans "Never. This is a 'one time only' reservation." %}</td>
{% endif %}
</tr></table>
{% if reservation.description %}
<h3>Description</h3>
<p>{{reservation.description}}</p>
{% endif %}

{% endblock %}

schedule/templates/schedule/reservation_form_base.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.timePicker.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_start_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_end_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_start_1").timePicker({
		startTime: new Date(0, 0, 0, 5, 00, 0), // Using string. Can take string or Date object.
  endTime: new Date(0, 0, 0, 22, 30, 0), // Using Date object here.
  show24Hours: true,
  separator: ':',
  step: 30});
        $("#id_end_1").timePicker({
		startTime: new Date(0, 0, 0, 5, 00, 0), // Using string. Can take string or Date object.
  endTime: new Date(0, 0, 0, 22, 30, 0), // Using Date object here.
  show24Hours: true,
  separator: ':',
  step: 30});
        $("#id_end_recurring_period").datepicker({dateFormat: $.datepicker.ATOM});
        var oldTime = $.timePicker("#id_start_1").getTime();
        $("#id_start_1").change(function() {
          if ($("#id_end_1").val()) { // Only update when second input has a value.
          // Calculate duration.
          var duration = ($.timePicker("#id_end_1").getTime() - oldTime);
          var time = $.timePicker("#id_start_1").getTime();
          // Calculate and update the time in the second input.
          $.timePicker("#id_end_1").setTime(new Date(new Date(time.getTime() + duration)));
          oldTime = time;
          }
        });
        // Validate.
        // TODO this should validate date AND time
        $("#id_end_1").change(function() {
          if($.timePicker("#id_start_1").getTime() > $.timePicker(this).getTime()) {
          $(this).addClass("error");
          }
          else {
          $(this).removeClass("error");
          }
        });
    });
    </script>
{% endblock %}

schedule/templates/schedule/room_compact_month.html
{% extends "base.html" %}
{% load scheduletags %}
{% block head_title %}{{calendar.name}}{% endblock %}
{% block body %}
<p align="center"><b>{{ calendar.name }}</b></p>
{% month_table calendar periods.month "small" %}
{% endblock %}

schedule/templates/schedule/room_month.html
{% extends "base.html" %}
{% load scheduletags %}
{% block head_title %}{{calendar.name}}{% endblock %}

{% block extra_head %}
    {{ block.super }}
    {% include "schedule/_dialogs.html" %}
{% endblock %}

{% block body %}
<div class="tablewrapper">
  <div class="calendarname">{{ calendar.name }}</div>
  
  {% prevnext "month_calendar" calendar.slug periods.month "F Y"%}
  <div class="now">
    <a href="{% url month_calendar calendar.slug %}">
      This month
    </a>
  </div>
  {% month_table calendar periods.month "regular" %}
</div>
{% endblock %}